import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/AppSidebar";
import { Toaster } from "@/components/ui/sonner";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <SidebarProvider>
          <AppSidebar />
          <BackgroundBeamsWithCollision>
            <main>
              <SidebarTrigger />
              {children}
              <Toaster position="bottom-right" />
            </main>
          </BackgroundBeamsWithCollision>
        </SidebarProvider>
      </body>
    </html>
  );
}
